# Generated by Django 5.1.3 on 2026-02-13 21:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_.-]+$')])),
                ('url_name', models.CharField(max_length=200)),
                ('url_kwargs_json', models.JSONField(blank=True, default=dict)),
                ('label_key', models.CharField(max_length=200)),
                ('default_label', models.CharField(max_length=200)),
                ('group_key', models.CharField(blank=True, default='', max_length=200)),
                ('keywords', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('vista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_pages', to='access_control.vista')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_search_is_acti_89a226_idx'), models.Index(fields=['key'], name='core_search_key_3a56bc_idx')],
            },
        ),
    ]
