# Generated by Django 5.1.3 on 2026-02-16 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaBibliotecaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa_id', models.IntegerField(blank=True, db_index=True, help_text='ID de empresa desde session', null=True)),
                ('action', models.CharField(choices=[('VIEW', 'Ver'), ('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('ERROR_403', 'Error 403 - Prohibido'), ('ERROR_500', 'Error 500 - Servidor')], max_length=20)),
                ('object_type', models.CharField(blank=True, help_text='Ej: Documento, Propiedad', max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, help_text='ID del objeto como string', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, help_text='GET, POST, etc.', max_length=10, null=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('querystring', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duración en milisegundos', null=True)),
                ('message_key', models.CharField(blank=True, help_text='Clave i18n del mensaje', max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, help_text='Metadata adicional sanitizada', null=True)),
                ('before', models.JSONField(blank=True, help_text='Estado anterior (UPDATE/DELETE)', null=True)),
                ('after', models.JSONField(blank=True, help_text='Estado posterior (UPDATE/CREATE)', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Auditoría Biblioteca',
                'verbose_name_plural': 'Eventos de Auditoría Biblioteca',
                'db_table': 'auditoria_biblioteca_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
