# Generated by Django 5.1.3 on 2026-02-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_auditoriabibliotecaevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriabibliotecaevent',
            name='action',
            field=models.CharField(choices=[('VIEW', 'Ver'), ('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('DOWNLOAD', 'Descargar'), ('SHARE', 'Compartir'), ('ERROR_403', 'Error 403 - Prohibido'), ('ERROR_500', 'Error 500 - Servidor')], max_length=20),
        ),
    ]
