# Generated by Django 5.1.3 on 2026-02-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_auditoriabibliotecaevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriabibliotecaevent',
            name='vista_nombre',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
