# Generated by Django 5.1.3 on 2026-08-24 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_auditoriagestiondteevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('app_label', models.CharField(db_index=True, max_length=50)),
                ('vista_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(max_length=500)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_user_presence',
                'indexes': [models.Index(fields=['app_label', 'empresa_id', 'last_seen'], name='auditoria_u_app_lab_5561a4_idx')],
            },
        ),
    ]
