# Generated by Django 5.1.3 on 2026-08-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_userpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriabibliotecaevent',
            name='action',
            field=models.CharField(choices=[('VIEW', 'Ver'), ('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('DOWNLOAD', 'Descargar'), ('SHARE', 'Compartir'), ('EXECUTE', 'Ejecutar'), ('ERROR_403', 'Error 403 - Prohibido'), ('ERROR_500', 'Error 500 - Servidor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriagestiondteevent',
            name='action',
            field=models.CharField(choices=[('VIEW', 'Ver'), ('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('DOWNLOAD', 'Descargar'), ('SHARE', 'Compartir'), ('EXECUTE', 'Ejecutar'), ('ERROR_403', 'Error 403 - Prohibido'), ('ERROR_500', 'Error 500 - Servidor')], max_length=20),
        ),
    ]
