# Generated by Django 5.1.3 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0007_alter_auditoriabibliotecaevent_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('app_label', models.CharField(db_index=True, max_length=50)),
                ('cutoff_datetime', models.DateTimeField(db_index=True)),
                ('source_min_id', models.BigIntegerField(blank=True, null=True)),
                ('source_max_id', models.BigIntegerField(blank=True, null=True)),
                ('company_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('archive_path', models.CharField(blank=True, default='', max_length=500)),
                ('archive_count', models.PositiveIntegerField(default=0)),
                ('source_checksum', models.CharField(blank=True, default='', max_length=128)),
                ('archive_checksum', models.CharField(blank=True, default='', max_length=128)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'auditoria_archive_batch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_label', 'cutoff_datetime', 'source_max_id'], name='auditoria_ar_app_lab_9b3a34_idx')],
            },
        ),
    ]
