# Generated by Django 5.1.3 on 2026-02-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_demoseedlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificacio_destina_f3d246_idx',
            old_name='notif_dest_isread_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificacio_empresa_2967e7_idx',
            old_name='notif_emp_dest_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificacio_dedupe__b4ba72_idx',
            old_name='notif_dedupe_dest_idx',
        ),
    ]
