version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/AppDocs  # Mapea tu proyecto
      - /home/computacion/db.sqlite3:/AppDocs/db.sqlite3  # Persistencia de la base de datos
    ports:
      - "8000:8000"

