# Generated by Django 4.2.4 on 2023-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
