# Generated by Django 5.1.3 on 2025-06-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_alter_avatar_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
