# Generated by Django 5.1.3 on 2026-01-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='avatares/default.jpg', null=True, upload_to='avatares'),
        ),
    ]
