# Generated by Django 4.2.3 on 2026-02-07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        ('acounts', '0004_alter_avatar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=150)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField()),
                ('smtp_user', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=False)),
                ('use_ssl', models.BooleanField(default=False)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('public_base_url', models.URLField()),
                ('default_from_email', models.EmailField(max_length=254)),
                ('default_from_name', models.CharField(max_length=150)),
                ('activation_ttl_hours', models.PositiveIntegerField(default=24)),
                ('reset_ttl_minutes', models.PositiveIntegerField(default=90)),
                ('max_failed_logins', models.PositiveIntegerField(default=5)),
                ('lock_minutes', models.PositiveIntegerField(default=15)),
                ('alerts_email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_alerts_configs', to='acounts.emailaccount')),
                ('notifications_email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notifications_configs', to='acounts.emailaccount')),
                ('security_email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_security_configs', to='acounts.emailaccount')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(condition=django.db.models.Q(is_active=True), fields=('is_active',), name='unique_active_system_config'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_base_url', models.URLField(blank=True, null=True)),
                ('from_name', models.CharField(blank=True, max_length=150, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activation_ttl_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('reset_ttl_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_failed_logins', models.PositiveIntegerField(blank=True, null=True)),
                ('lock_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('alerts_email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_alerts_configs', to='acounts.emailaccount')),
                ('notifications_email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_notifications_configs', to='acounts.emailaccount')),
                ('security_email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_security_configs', to='acounts.emailaccount')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='access_control.empresa')),
            ],
        ),
    ]
