# Generated by Django 4.2.2 on 2026-02-07

from django.db import migrations, models
import django.db.models.deletion

try:
    JSONField = models.JSONField
except AttributeError:
    JSONField = models.TextField


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0005_emailaccount_systemconfig_companyconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('ACTIVATE', 'ACTIVATE')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_tokens', to='auth.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to='auth.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'purpose'], name='acounts_use_user_id_65a30d_idx')],
            },
        ),
    ]
