# Generated by Django 5.1.3 on 2026-02-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0006_useremailtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useremailtoken',
            new_name='acounts_use_user_id_02038b_idx',
            old_name='acounts_use_user_id_65a30d_idx',
        ),
    ]
