# Generated by Django 5.1.3 on 2026-08-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0008_merge_avatar_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='username',
        ),
    ]
