# Generated by Django 4.2.3 on 2023-07-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_miusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiUsuario',
        ),
    ]
