# Generated by Django 4.2.3 on 2023-07-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_delete_miusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Nombre_documento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
