# Generated by Django 4.2.4 on 2023-08-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_conversacion_mensaje_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dni',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profesion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
