# Generated by Django 4.2.4 on 2023-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='dni',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='profesion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
