# Generated by Django 4.2.3 on 2023-08-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_avatar_email_avatar_first_name_avatar_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
