# Generated by Django 4.2.3 on 2023-08-06 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='conversacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.DeleteModel(
            name='Conversacion',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
