# Generated by Django 4.2.4 on 2023-08-07 14:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_delete_about_tipodocumento_descricion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='descricion',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
    ]
