# Generated by Django 4.2.4 on 2023-08-09 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_alter_tipodocumento_descricion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
