# Generated by Django 4.2.4 on 2023-08-14 15:53

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_documento_fecha_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='archivos_documentos/', validators=[biblioteca.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='telefono',
            field=models.CharField(default='452379500', max_length=20),
        ),
    ]
