# Generated by Django 4.2.4 on 2023-08-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_propiedad_descripcion_alter_documento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Nombre_documento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='rol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
