# Generated by Django 5.1.3 on 2024-11-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0017_alter_documento_nombre_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Nombre_documento',
            new_name='nombre_documento',
        ),
    ]
