# Generated by Django 5.1.3 on 2025-05-29 01:32

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0018_rename_nombre_documento_documento_nombre_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=biblioteca.models.archivo_documento_path, validators=[biblioteca.models.validate_file_extension]),
        ),
    ]
