# Generated by Django 5.1.3 on 2026-01-28 20:40

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0019_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='rut',
            field=models.CharField(max_length=20, unique=True, validators=[biblioteca.models.validar_rut]),
        ),
    ]
