# Generated by Django 5.1.3 on 2026-01-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('second_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('document_type', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=20)),
                ('code_sheet', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=20)),
                ('office_number', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('office_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('birthday', models.DateField()),
                ('active_since', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_period', models.CharField(max_length=20)),
                ('advance_payment', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('private_role', models.BooleanField(default=False)),
                ('progressive_vacations_start', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=50)),
                ('health_company', models.CharField(max_length=50)),
                ('pension_regime', models.CharField(max_length=50)),
                ('pension_fund', models.CharField(max_length=50)),
                ('afc', models.CharField(max_length=20)),
                ('retired', models.BooleanField(default=False)),
                ('mes', models.PositiveSmallIntegerField(default=1)),
                ('anio', models.PositiveSmallIntegerField(default=2026)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-anio', '-mes', 'full_name'],
            },
        ),
    ]
