# Generated by Django 5.1.3 on 2026-02-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='mes',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
