# Generated by Django 5.1.3 on 2026-09-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_alter_persona_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='mes',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
