# Generated by Django 5.1.3 on 2026-09-10 22:44

import evaluaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_alter_persona_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='mes',
            field=models.PositiveSmallIntegerField(default=evaluaciones.models.current_month),
        ),
    ]
