# Generated by Django 5.1.3 on 2025-05-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmovimientosDetalle19',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('linea', models.FloatField()),
                ('rut', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('codigo', models.CharField(max_length=13)),
                ('descripcion', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('uxc', models.FloatField()),
                ('unidades', models.FloatField()),
                ('precio', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
                ('costoventa', models.FloatField()),
                ('bodega', models.CharField(max_length=2)),
                ('bodegatraspaso', models.CharField(max_length=2)),
                ('stocktransaccion', models.FloatField()),
            ],
            options={
                'db_table': 'l_movimientos_detalle_19',
                'managed': False,
            },
        ),
    ]
