# Generated by Django 5.1.3 on 2026-09-07 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0011_create_gestion_dte_auditoria_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('prioridad', models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('NORMAL', 'NORMAL'), ('URGENTE', 'URGENTE'), ('CRITICA', 'CRITICA')], default='NORMAL', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('PUBLICADA', 'PUBLICADA')], default='BORRADOR', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='access_control.empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'estado'], name='tareas_tare_empresa_f82081_idx'), models.Index(fields=['empresa', 'fecha_creacion'], name='tareas_tare_empresa_8defd5_idx')],
            },
        ),
    ]
