# Generated by Django 5.1.3 on 2026-09-08 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_phase2(apps, schema_editor):
    Tarea = apps.get_model("tareas", "Tarea")
    CorrelativoEmpresa = apps.get_model("tareas", "CorrelativoEmpresa")
    db_alias = schema_editor.connection.alias

    empresa_ids = (
        Tarea.objects.using(db_alias)
        .values_list("empresa_id", flat=True)
        .distinct()
    )
    for empresa_id in empresa_ids:
        tareas = list(
            Tarea.objects.using(db_alias)
            .filter(empresa_id=empresa_id)
            .order_by("fecha_creacion", "id")
        )
        used_numbers = set()
        pending = []
        for tarea in tareas:
            correlativo = tarea.correlativo or ""
            if len(correlativo) == 8 and correlativo[0] in {"A", "B"} and correlativo[1:].isdigit():
                number = int(correlativo[1:])
                if number not in used_numbers:
                    used_numbers.add(number)
                    expected_prefix = "B" if tarea.estado == "PUBLICADA" else "A"
                    tarea.correlativo = f"{expected_prefix}{number:07d}"
                else:
                    pending.append(tarea)
            else:
                pending.append(tarea)

        next_number = 1
        for tarea in pending:
            while next_number in used_numbers:
                next_number += 1
            prefix = "B" if tarea.estado == "PUBLICADA" else "A"
            tarea.correlativo = f"{prefix}{next_number:07d}"
            used_numbers.add(next_number)
            next_number += 1

        for tarea in tareas:
            if tarea.estado == "PUBLICADA":
                tarea.estado = "ACTIVA"
        if tareas:
            Tarea.objects.using(db_alias).bulk_update(
                tareas, ["correlativo", "estado"]
            )

        sequence, _created = CorrelativoEmpresa.objects.using(db_alias).get_or_create(
            empresa_id=empresa_id,
            defaults={"siguiente_numero": (max(used_numbers) + 1) if used_numbers else 1},
        )
        if not _created:
            sequence.siguiente_numero = max(used_numbers) + 1 if used_numbers else 1
            sequence.save(using=db_alias, update_fields=["siguiente_numero"])


def reverse_phase2(apps, schema_editor):
    # The forward backfill is intentionally not destructive on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0011_create_gestion_dte_auditoria_view'),
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelativoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siguiente_numero', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TareaAnulacionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=32)),
                ('fechas_pendientes_confirmacion', models.BooleanField(default=False)),
                ('timestamp_anulacion', models.DateTimeField(auto_now_add=True)),
                ('timestamp_reactivacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TareaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=10)),
                ('comentario', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TareaTransicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_origen', models.CharField(max_length=32)),
                ('estado_destino', models.CharField(blank=True, default='', max_length=32)),
                ('accion_evento', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='correlativo',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechas_pendientes_confirmacion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('ACTIVA', 'ACTIVA'), ('GESTION', 'GESTION'), ('PENDIENTE_APROBACION_CIERRE', 'PENDIENTE_APROBACION_CIERRE'), ('CERRADA', 'CERRADA'), ('ANULADA', 'ANULADA')], default='BORRADOR', max_length=32),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['empresa', 'correlativo'], name='tareas_tare_empresa_e8cfb3_idx'),
        ),
        migrations.AddField(
            model_name='correlativoempresa',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correlativo_tareas', to='access_control.empresa'),
        ),
        migrations.AddField(
            model_name='tareaanulacionsnapshot',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_anulacion', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='tareaanulacionsnapshot',
            name='usuario_anulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareaanulacionsnapshot',
            name='usuario_reactivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_reactivadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareacierre',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='tareacierre',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_cierres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareatransicion',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transiciones', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='tareatransicion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_transiciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='correlativoempresa',
            index=models.Index(fields=['empresa'], name='tareas_corr_empresa_322dab_idx'),
        ),
        migrations.AddIndex(
            model_name='tareatransicion',
            index=models.Index(fields=['tarea', 'timestamp'], name='tareas_tare_tarea_i_78e961_idx'),
        ),
        migrations.RunPython(backfill_phase2, reverse_phase2),
        migrations.AlterField(
            model_name='tarea',
            name='correlativo',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechas_pendientes_confirmacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('empresa', 'correlativo'), name='tareas_empresa_correlativo_uniq'),
        ),
    ]
