# Generated by Django 5.1.3 on 2026-09-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_correlativoempresa_tareaanulacionsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='cierre_completado',
            field=models.BooleanField(default=False),
        ),
    ]
