# Generated by Django 5.1.3 on 2026-09-08 13:17

from django.db import migrations, models


def migrar_anuladas_a_flag(apps, schema_editor):
    """Migra tareas históricas con estado=ANULADA al nuevo flag `anulada`.

    Para cada tarea con estado=ANULADA: pone anulada=True y restaura el estado
    funcional desde el último TareaAnulacionSnapshot.estado_anterior válido. Si existe
    una tarea ANULADA sin snapshot válido, ABORTA la migración (no inventa estado).
    """
    Tarea = apps.get_model("tareas", "Tarea")
    TareaAnulacionSnapshot = apps.get_model("tareas", "TareaAnulacionSnapshot")

    anuladas = Tarea.objects.filter(estado="ANULADA")
    sin_snapshot = []
    for tarea in anuladas:
        snapshot = (
            TareaAnulacionSnapshot.objects.filter(tarea=tarea)
            .order_by("-timestamp_anulacion")
            .first()
        )
        if snapshot is None or not snapshot.estado_anterior:
            sin_snapshot.append(tarea.pk)
            continue
        tarea.anulada = True
        tarea.estado = snapshot.estado_anterior
        tarea.save(update_fields=["anulada", "estado"])

    if sin_snapshot:
        raise RuntimeError(
            "Migración abortada: tareas con estado=ANULADA sin snapshot válido "
            f"(pks={sin_snapshot}). Revisar datos antes de continuar."
        )


def revertir_flag_a_estado(apps, schema_editor):
    """Reversa: vuelve a estado=ANULADA las tareas con anulada=True."""
    Tarea = apps.get_model("tareas", "Tarea")
    Tarea.objects.filter(anulada=True).update(estado="ANULADA", anulada=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tarea_cierre_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        # Migración de datos ANTES de endurecer el campo estado (retirar ANULADA).
        migrations.RunPython(migrar_anuladas_a_flag, revertir_flag_a_estado),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('ACTIVA', 'ACTIVA'), ('GESTION', 'GESTION'), ('PENDIENTE_APROBACION_CIERRE', 'PENDIENTE_APROBACION_CIERRE'), ('CERRADA', 'CERRADA')], default='BORRADOR', max_length=32),
        ),
    ]
