# Generated by Django 5.1.3 on 2026-09-08 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_anulada_alter_tarea_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='tareas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas_tareas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tarea', 'usuario', 'leido'], name='tareas_tare_tarea_i_cf4777_idx')],
                'constraints': [models.UniqueConstraint(fields=('tarea', 'usuario'), name='tareas_lectura_unica_por_usuario')],
            },
        ),
        migrations.CreateModel(
            name='TareaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CREADOR', 'CREADOR'), ('RESPONSABLE_LIDER', 'RESPONSABLE_LIDER'), ('SUPERVISOR', 'SUPERVISOR'), ('AUTORIZADOR', 'AUTORIZADOR'), ('PARTICIPANTE', 'PARTICIPANTE'), ('INVITADO_OBSERVADOR', 'INVITADO_OBSERVADOR')], default='PARTICIPANTE', max_length=32)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantes', to='tareas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones_tareas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tarea', 'usuario'], name='tareas_tare_tarea_i_003772_idx')],
                'constraints': [models.UniqueConstraint(fields=('tarea', 'usuario'), name='tareas_participante_unico_por_tarea')],
            },
        ),
        migrations.CreateModel(
            name='TareaReasignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, default='')),
                ('responsable_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_reasignadas_desde', to=settings.AUTH_USER_MODEL)),
                ('responsable_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_reasignadas_a', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones', to='tareas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_reasignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tarea', 'fecha'], name='tareas_tare_tarea_i_bce944_idx')],
            },
        ),
    ]
