# Generated by Django 5.1.3 on 2026-09-08 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_tarealectura_tareaparticipante_tareareasignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('hija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_padre', to='tareas.tarea')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_hijas', to='tareas.tarea')),
            ],
            options={
                'indexes': [models.Index(fields=['padre'], name='tareas_tare_padre_i_941c9c_idx'), models.Index(fields=['hija'], name='tareas_tare_hija_id_39eace_idx')],
                'constraints': [models.UniqueConstraint(fields=('hija',), name='tareas_relacion_hija_unico_padre')],
            },
        ),
    ]
