# Generated by Django 5.1.3 on 2026-09-08 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0012_rename_settings_vistas_merge_permisos'),
        ('tareas', '0007_swap_correlativo_prefixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREADO', 'CREADO'), ('CERRADO', 'CERRADO'), ('TAREA_CREADA', 'TAREA_CREADA')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_derivadas', to='tareas.tarea'),
        ),
        migrations.CreateModel(
            name='CorrelativoTodoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siguiente_numero', models.PositiveIntegerField(default=1)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correlativo_todos', to='access_control.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=9)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], default='ABIERTO', max_length=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('comentario_cierre', models.TextField(blank=True, default='')),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='todos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todos_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todos', to='access_control.empresa')),
                ('todo_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='episodios_siguientes', to='tareas.todo')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='todo_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_origen', to='tareas.todo'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('todo_origen__isnull', True), ('tarea_origen__isnull', True), _connector='OR'), name='tareas_unico_origen_canonico'),
        ),
        migrations.AddField(
            model_name='todoevento',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_todo', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='todoevento',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='tareas.todo'),
        ),
        migrations.AddField(
            model_name='todoevento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_todo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='correlativotodoempresa',
            index=models.Index(fields=['empresa'], name='tareas_corr_empresa_ef5395_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['empresa', 'estado'], name='tareas_todo_empresa_dab7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['empresa', 'fecha_creacion'], name='tareas_todo_empresa_5f6d14_idx'),
        ),
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(fields=('empresa', 'correlativo'), name='tareas_empresa_todo_correlativo_uniq'),
        ),
        migrations.AddIndex(
            model_name='todoevento',
            index=models.Index(fields=['todo', 'timestamp'], name='tareas_todo_todo_id_222afd_idx'),
        ),
    ]
