# Generated by Django 5.1.3 on 2026-09-08 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


CAUSAS_ATRASO = (
    ("IMPOSIBILIDAD_TECNICA", "Imposibilidad técnica"),
    ("ATRASO_IMPORTACION", "Atraso importación"),
    ("PERMISOS_MUNICIPALES", "Permisos municipales"),
    ("PROBLEMAS_ESCRITURAS", "Problemas de escrituras"),
    ("CAUSAS_INTERNAS", "Causas internas"),
    ("CAUSAS_EXTERNAS", "Causas externas"),
)


def seed_causas_atraso(apps, schema_editor):
    causa_model = apps.get_model("tareas", "CausaAtraso")
    for codigo, nombre in CAUSAS_ATRASO:
        causa_model.objects.update_or_create(
            codigo=codigo,
            defaults={"nombre": nombre},
        )


def unseed_causas_atraso(apps, schema_editor):
    causa_model = apps.get_model("tareas", "CausaAtraso")
    causa_model.objects.filter(codigo__in=[codigo for codigo, _ in CAUSAS_ATRASO]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_todoevento_tarea_tarea_origen_correlativotodoempresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaAtraso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.RunPython(seed_causas_atraso, unseed_causas_atraso),
        migrations.AddField(
            model_name='tarea',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_cumplimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_tope',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reprogramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tope_anterior', models.DateField()),
                ('fecha_tope_nueva', models.DateField()),
                ('justificacion', models.TextField()),
                ('fecha_operacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('causas', models.ManyToManyField(related_name='reprogramaciones', to='tareas.causaatraso')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprogramaciones', to='tareas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprogramaciones_tareas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tarea', 'fecha_operacion'], name='tareas_repr_tarea_i_f8d80e_idx')],
            },
        ),
    ]
