# Generated by Django 5.1.3 on 2026-09-08 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_causaatraso_tarea_fecha_asignacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('hecho', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_tareas', to='tareas.tarea')),
            ],
            options={
                'ordering': ['fecha_creacion', 'pk'],
                'indexes': [models.Index(fields=['tarea', 'hecho'], name='tareas_mini_tarea_i_657b89_idx')],
            },
        ),
    ]
