# Generated by Django 5.1.3 on 2026-09-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_minitarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('MANUAL', 'Manual'), ('PONDERADO', 'Ponderado')], default='MANUAL', max_length=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='avance', to='tareas.tarea')),
            ],
        ),
    ]
