# Generated by Django 5.1.3 on 2026-09-08 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cumplimiento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hitos', to='tareas.tarea')),
            ],
            options={
                'ordering': ['fecha_creacion', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cumplimiento__gte', 0), ('cumplimiento__lte', 100)), name='tareas_hito_cumplimiento_rango'), models.CheckConstraint(condition=models.Q(('peso__gt', 0)), name='tareas_hito_peso_positivo')],
            },
        ),
    ]
