# Generated by Django 5.1.3 on 2026-09-08 20:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_hito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COTIZACION', 'Cotización'), ('FOTOGRAFIA', 'Fotografía'), ('INFORME', 'Informe'), ('ORDEN_TRABAJO', 'Orden de trabajo'), ('FACTURA', 'Factura'), ('CONTRATO', 'Contrato'), ('PLANO', 'Plano'), ('CERTIFICADO', 'Certificado'), ('OTRO', 'Otro')], max_length=20)),
                ('archivo', models.FileField(blank=True, default='', upload_to='tareas/documentos/')),
                ('url', models.URLField(blank=True, default='')),
                ('fecha_documento', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='', max_length=20)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tareas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tareas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_documentos_tareas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='tareas.documentotarea')),
            ],
            options={
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_cierre', to='tareas.documentotarea')),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidencia_cierre', to='tareas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_cierre_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='documentotarea',
            index=models.Index(fields=['tarea', 'tipo'], name='tareas_docu_tarea_i_9efff0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotarea',
            index=models.Index(fields=['tarea', 'estado'], name='tareas_docu_tarea_i_54596b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentohistorial',
            index=models.Index(fields=['documento', 'fecha'], name='tareas_docu_documen_236103_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciacierre',
            index=models.Index(fields=['tarea', 'requerida'], name='tareas_evid_tarea_i_412f46_idx'),
        ),
    ]
