# Generated by Django 5.1.3 on 2026-09-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_authorized_hito(apps, schema_editor):
    Hito = apps.get_model("tareas", "Hito")
    HitoHistorial = apps.get_model("tareas", "HitoHistorial")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    null_ids = list(
        Hito.objects.filter(responsable__isnull=True).values_list("pk", flat=True)
    )
    if not null_ids:
        return
    unexpected = [pk for pk in null_ids if pk != 1]
    if unexpected:
        raise RuntimeError(
            "UNEXPECTED_HISTORICAL_DATA: Hitos sin responsable fuera de pk=1: "
            + ", ".join(str(pk) for pk in unexpected)
        )

    hito = Hito.objects.filter(pk=1, responsable__isnull=True).select_related("tarea__empresa").first()
    if hito is None:
        raise RuntimeError(
            "UNEXPECTED_HISTORICAL_DATA: no se encontró Hito pk=1 sin responsable."
        )

    tarea = hito.tarea
    empresa = tarea.empresa
    if (
        hito.nombre != "Pedir cotizacion"
        or tarea.titulo != "compra de latas"
        or tarea.correlativo != "A0000002"
        or empresa.codigo != "00"
        or (empresa.descripcion or "") != "empresa base"
    ):
        raise RuntimeError(
            "UNEXPECTED_HISTORICAL_DATA: la identidad contractual de Hito pk=1 no coincide."
        )

    admin = User.objects.filter(username="admin").first()
    if admin is None:
        raise RuntimeError("UNEXPECTED_HISTORICAL_DATA: no existe el usuario admin.")

    hito.responsable_id = admin.pk
    hito.save(update_fields=["responsable"])
    HitoHistorial.objects.create(
        hito_id=hito.pk,
        tipo_evento="CREACION",
        usuario_id=admin.pk,
        datos_anteriores={},
        datos_nuevos={
            "nombre": hito.nombre,
            "cumplimiento": str(hito.cumplimiento),
            "peso": str(hito.peso),
            "responsable": admin.pk,
            "anulado": False,
        },
        motivo="Backfill histórico autorizado para Hito pk=1.",
    )


def reverse_authorized_hito(apps, schema_editor):
    Hito = apps.get_model("tareas", "Hito")
    HitoHistorial = apps.get_model("tareas", "HitoHistorial")
    HitoHistorial.objects.filter(hito_id=1).delete()
    Hito.objects.filter(pk=1).update(responsable=None)


class Migration(migrations.Migration):
    dependencies = [
        ("tareas", "0013_documentotarea_documentohistorial_evidenciacierre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hito",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hitos_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hito",
            name="anulado",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="HitoHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("CREACION", "Creación"),
                            ("CAMBIO_NOMBRE", "Cambio de nombre"),
                            ("CAMBIO_CUMPLIMIENTO", "Cambio de cumplimiento"),
                            ("CAMBIO_PESO", "Cambio de peso"),
                            ("REASIGNACION", "Reasignación"),
                            ("ANULACION", "Anulación"),
                            ("REACTIVACION", "Reactivación"),
                            ("ELIMINACION_FISICA", "Eliminación física"),
                        ],
                        max_length=32,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("datos_anteriores", models.JSONField(default=dict)),
                ("datos_nuevos", models.JSONField(default=dict)),
                ("motivo", models.TextField(blank=True, default="")),
                (
                    "hito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="tareas.hito",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_hitos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "pk"],
                "indexes": [
                    models.Index(
                        fields=["hito", "fecha"],
                        name="tareas_hh_hito_fecha_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_authorized_hito, reverse_authorized_hito),
        migrations.AlterField(
            model_name="hito",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hitos_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
