# Generated by Django 5.1.3 on 2026-09-14 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0018_hito_completitud_hitoevidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RondaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('minimo_cotizaciones', models.PositiveIntegerField(default=3)),
                ('estado', models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('CERRADA', 'CERRADA')], default='ABIERTA', max_length=8)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas_cotizacion', to='tareas.tarea')),
            ],
            options={
                'ordering': ['tarea_id', 'numero'],
                'indexes': [models.Index(fields=['tarea', 'estado'], name='tareas_rond_tarea_i_41f0c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('tarea', 'numero'), name='tareas_ronda_tarea_numero_unico'), models.CheckConstraint(condition=models.Q(('numero__gte', 1)), name='tareas_ronda_numero_positivo'), models.CheckConstraint(condition=models.Q(('minimo_cotizaciones__gte', 1)), name='tareas_ronda_minimo_positivo')],
            },
        ),
    ]
