# Generated by Django 5.1.3 on 2026-09-14 20:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0019_rondacotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('RECIBIDA', 'RECIBIDA'), ('SELECCIONADA', 'SELECCIONADA'), ('DESCARTADA', 'DESCARTADA')], default='RECIBIDA', max_length=13)),
                ('fecha_cotizacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, default='')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='tareas.rondacotizacion')),
            ],
            options={
                'ordering': ['ronda_id', 'version', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_archivo', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('JPEG', 'JPEG'), ('PNG', 'PNG'), ('DOC', 'DOC'), ('DOCX', 'DOCX'), ('XLS', 'XLS'), ('XLSX', 'XLSX')], max_length=4)),
                ('archivo', models.FileField(blank=True, default='', upload_to='tareas/cotizaciones/')),
                ('url', models.URLField(blank=True, default='')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tareas.cotizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cotizaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['ronda', 'estado'], name='tareas_coti_ronda_i_7fbd4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='tareas_cotizacion_version_positiva'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', Decimal('0'))), name='tareas_cotizacion_monto_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='documentocotizacion',
            index=models.Index(fields=['cotizacion', 'fecha'], name='tareas_docu_cotizac_ee3db1_idx'),
        ),
    ]
