# Generated by Django 5.1.3 on 2026-09-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('tareas', '0020_cotizacion_documentocotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='proveedores.proveedor'),
        ),
    ]
