# Generated by Django 5.1.3 on 2026-09-16 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0013_permiso_ver_perfilaccesodetalle_ver'),
        ('organizacion', '0001_initial'),
        ('tareas', '0021_cotizacion_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='organizacion.departamento'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='organizacion.local'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_ambito',
            field=models.CharField(blank=True, choices=[('LOCAL', 'LOCAL'), ('DEPARTAMENTO', 'DEPARTAMENTO')], max_length=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('departamento__isnull', True), ('local__isnull', True), ('tipo_ambito__isnull', True)), models.Q(('departamento__isnull', True), ('local__isnull', True), ('tipo_ambito', '')), models.Q(('departamento__isnull', True), ('local__isnull', False), ('tipo_ambito', 'LOCAL')), models.Q(('departamento__isnull', False), ('local__isnull', True), ('tipo_ambito', 'DEPARTAMENTO')), _connector='OR'), name='tareas_ambito_xor'),
        ),
    ]
