# Generated by Django 5.1.3 on 2026-09-16 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0013_permiso_ver_perfilaccesodetalle_ver'),
        ('organizacion', '0001_initial'),
        ('tareas', '0022_tarea_departamento_tarea_local_tarea_tipo_ambito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReunionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_hora_programada', models.DateTimeField()),
                ('modalidad', models.CharField(choices=[('ZOOM', 'ZOOM'), ('PRESENCIAL', 'PRESENCIAL')], max_length=10)),
                ('lugar_o_enlace', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_ambito', models.CharField(choices=[('LOCAL', 'LOCAL'), ('DEPARTAMENTO', 'DEPARTAMENTO')], max_length=12)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'PLANIFICADA'), ('REALIZADA', 'REALIZADA')], default='PLANIFICADA', max_length=11)),
                ('convocada_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_revision_creadas', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_revision', to='organizacion.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_revision', to='access_control.empresa')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_revision', to='organizacion.local')),
                ('tarea_planificada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reunion_revision', to='tareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='ReunionParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_revision_participante', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='tareas.reunionrevision')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reunion', 'usuario'), name='unique_reunion_revision_participante')],
            },
        ),
        migrations.CreateModel(
            name='ReunionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('comentario_revision', models.TextField(blank=True, default='')),
                ('comentario_cierre', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='tareas.reunionrevision')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_revision', to='tareas.tarea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reunion', 'tarea'), name='unique_reunion_revision_tarea'), models.UniqueConstraint(fields=('reunion', 'orden'), name='unique_reunion_revision_orden')],
            },
        ),
    ]
