# Generated by Django 5.1.3 on 2026-09-16 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0023_reunionrevision_reunionparticipante_reuniontarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionSimilitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umbral_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supera_umbral', models.BooleanField()),
                ('decision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('MISMO_PROBLEMA', 'Mismo problema'), ('DISTINTO_PROBLEMA', 'Distinto problema')], default='PENDIENTE', max_length=20)),
                ('confirmada_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_similitud_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_similitud', to='tareas.tarea')),
                ('tarea_candidata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_como_candidata', to='tareas.tarea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tarea', 'tarea_candidata'), name='unique_evaluacion_similitud_pareja'), models.CheckConstraint(condition=models.Q(('tarea', models.F('tarea_candidata')), _negated=True), name='evaluacion_similitud_tareas_distintas'), models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='evaluacion_similitud_porcentaje_rango'), models.CheckConstraint(condition=models.Q(('umbral_aplicado__gte', 0), ('umbral_aplicado__lte', 100)), name='evaluacion_similitud_umbral_rango')],
            },
        ),
    ]
