# Generated by Django 5.1.3 on 2026-09-16 20:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0013_permiso_ver_perfilaccesodetalle_ver'),
        ('tareas', '0024_evaluacionsimilitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralSimilitudEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='umbrales_similitud_actualizados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='umbral_similitud', to='access_control.empresa')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='umbral_similitud_empresa_porcentaje_rango')],
            },
        ),
    ]
