# Generated by Django 5.1.3 on 2026-09-16 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0025_umbralsimilitudempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('revocado_at', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlaces_tareas_creados', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlaces_tareas_recibidos', to=settings.AUTH_USER_MODEL)),
                ('revocado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_tareas_revocados', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='tareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAccesoEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('ACCESO_OK', 'ACCESO_OK'), ('RECHAZADO_USUARIO', 'RECHAZADO_USUARIO'), ('RECHAZADO_EMPRESA', 'RECHAZADO_EMPRESA'), ('RECHAZADO_EXPIRADO', 'RECHAZADO_EXPIRADO'), ('RECHAZADO_REVOCADO', 'RECHAZADO_REVOCADO')], max_length=24)),
                ('enlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_acceso', to='tareas.enlacetarea')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_acceso_enlaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
