# Generated by Django 5.1.3 on 2026-09-25 00:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0026_enlacetarea_eventoaccesoenlace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oculto', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_tareas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='tareas.tarea')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='tarealectura',
            name='comentario_leido_hasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecturas_hasta_aqui', to='tareas.comentario'),
        ),
        migrations.CreateModel(
            name='ComentarioAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='tareas.comentario')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos_comentarios', to='tareas.documentotarea')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioPausaLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField(blank=True, null=True)),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pausas_comentarios', to='tareas.tarealectura')),
            ],
            options={
                'ordering': ['desde', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CREADO', 'CREADO'), ('EDITADO', 'EDITADO'), ('OCULTADO', 'OCULTADO'), ('RESTAURADO', 'RESTAURADO')], max_length=10)),
                ('numero_version', models.PositiveIntegerField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_comentarios_tareas', to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='tareas.comentario')),
            ],
            options={
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioVersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_comentarios', to='tareas.documentotarea')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tareas.comentarioversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['tarea', 'created_at', 'id'], name='tareas_come_tarea_i_d9a726_idx'),
        ),
        migrations.AddConstraint(
            model_name='comentarioadjunto',
            constraint=models.UniqueConstraint(fields=('comentario', 'documento'), name='tareas_com_adjunto_unico'),
        ),
        migrations.AddIndex(
            model_name='comentariopausalectura',
            index=models.Index(fields=['lectura', 'desde'], name='tareas_come_lectura_d36bd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='comentariopausalectura',
            constraint=models.CheckConstraint(condition=models.Q(('hasta__isnull', True), ('hasta__gte', models.F('desde')), _connector='OR'), name='tareas_com_pausa_intervalo'),
        ),
        migrations.AddIndex(
            model_name='comentarioversion',
            index=models.Index(fields=['comentario', 'fecha', 'id'], name='tareas_come_comenta_0c6900_idx'),
        ),
        migrations.AddConstraint(
            model_name='comentarioversion',
            constraint=models.UniqueConstraint(fields=('comentario', 'numero_version'), name='tareas_com_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='comentarioversiondocumento',
            constraint=models.UniqueConstraint(fields=('version', 'documento'), name='tareas_com_ver_doc_unico'),
        ),
    ]
