# Generated by Django 5.1.3 on 2026-10-02 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0027_comentario_tarealectura_comentario_leido_hasta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniTareaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CIERRE', 'CIERRE'), ('REAPERTURA', 'REAPERTURA')], max_length=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField()),
                ('destinatarios_notificacion', models.JSONField(default=list)),
                ('destinatarios_email', models.JSONField(default=list)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_mini_tareas', to=settings.AUTH_USER_MODEL)),
                ('mini_tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='tareas.minitarea')),
            ],
            options={
                'ordering': ['fecha', 'pk'],
                'indexes': [models.Index(fields=['mini_tarea', 'fecha'], name='tareas_mini_mini_ta_288ed4_idx')],
            },
        ),
    ]
