# Generated by Django 5.1.3 on 2026-10-02 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0028_minitareaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='minitareaevento',
            name='comentario_feed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evento_cierre_minitarea', to='tareas.comentario'),
        ),
    ]
