# Generated by Django 5.1.3 on 2026-02-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_mensajeleido_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mensajeleido',
            new_name='chat_mensaj_user_id_019acb_idx',
            old_name='chat_mensaj_user_id_4b5d6d_idx',
        ),
        migrations.RenameIndex(
            model_name='mensajeleido',
            new_name='chat_mensaj_empresa_42b7c5_idx',
            old_name='chat_mensaj_emprea_76b5a6_idx',
        ),
    ]
