# Generated by Django 5.1.3 on 2025-05-29 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_layout', models.CharField(blank=True, max_length=50, null=True)),
                ('data_bs_theme', models.CharField(blank=True, max_length=50, null=True)),
                ('data_sidebar_visibility', models.CharField(blank=True, max_length=50, null=True)),
                ('data_layout_width', models.CharField(blank=True, max_length=50, null=True)),
                ('data_layout_position', models.CharField(blank=True, max_length=50, null=True)),
                ('data_topbar', models.CharField(blank=True, max_length=50, null=True)),
                ('data_sidebar_size', models.CharField(blank=True, max_length=50, null=True)),
                ('data_layout_style', models.CharField(blank=True, max_length=50, null=True)),
                ('data_sidebar', models.CharField(blank=True, max_length=50, null=True)),
                ('data_sidebar_image', models.CharField(blank=True, max_length=50, null=True)),
                ('data_preloader', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
