# Generated by Django 5.1.3 on 2025-05-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='data_bs_theme',
            field=models.CharField(blank=True, default='light', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_layout',
            field=models.CharField(blank=True, default='vertical', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_layout_position',
            field=models.CharField(blank=True, default='fixed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_layout_style',
            field=models.CharField(blank=True, default='default', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_layout_width',
            field=models.CharField(blank=True, default='fluid', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_preloader',
            field=models.CharField(blank=True, default='disable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sidebar',
            field=models.CharField(blank=True, default='dark', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sidebar_image',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sidebar_size',
            field=models.CharField(blank=True, default='lg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sidebar_visibility',
            field=models.CharField(blank=True, default='show', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_topbar',
            field=models.CharField(blank=True, default='light', max_length=50, null=True),
        ),
    ]
