# Generated by Django 5.1.3 on 2025-05-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_userpreferences_data_bs_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_encryption',
            field=models.CharField(blank=True, choices=[('NONE', 'Ninguno'), ('SSL', 'SSL'), ('TLS', 'TLS')], default='SSL', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_protocol',
            field=models.CharField(blank=True, choices=[('IMAP', 'IMAP'), ('POP3', 'POP3')], default='IMAP', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='send_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='send_headers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='smtp_encryption',
            field=models.CharField(blank=True, choices=[('NONE', 'Ninguno'), ('SSL', 'SSL'), ('STARTTLS', 'STARTTLS')], default='STARTTLS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
