# Generated by Django 5.1.3 on 2025-05-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_userpreferences_email_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='data_bs_theme',
            field=models.CharField(blank=True, choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_layout',
            field=models.CharField(blank=True, choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('twocolumn', 'Two Column'), ('semibox', 'Semi Boxed')], default='vertical', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_layout_position',
            field=models.CharField(blank=True, choices=[('fixed', 'Fijo'), ('scrollable', 'Desplazable')], default='fixed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_layout_style',
            field=models.CharField(blank=True, choices=[('default', 'Por Defecto'), ('detached', 'Separado')], default='default', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_layout_width',
            field=models.CharField(blank=True, choices=[('fluid', 'Ancho Fluido'), ('boxed', 'Boxed')], default='fluid', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_preloader',
            field=models.CharField(blank=True, choices=[('disable', 'Desactivado'), ('enable', 'Activado')], default='disable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sidebar',
            field=models.CharField(blank=True, choices=[('dark', 'Oscuro'), ('light', 'Claro'), ('gradient', 'Gradiente')], default='dark', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sidebar_image',
            field=models.CharField(blank=True, choices=[('none', 'Sin imagen'), ('img-1', 'Imagen 1'), ('img-2', 'Imagen 2'), ('img-3', 'Imagen 3'), ('img-4', 'Imagen 4')], default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sidebar_size',
            field=models.CharField(blank=True, choices=[('lg', 'Grande'), ('md', 'Mediano'), ('sm', 'Pequeño'), ('sm-hover', 'Pequeño (Hover)')], default='lg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sidebar_visibility',
            field=models.CharField(blank=True, choices=[('show', 'Mostrar'), ('hidden', 'Ocultar')], default='show', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_topbar',
            field=models.CharField(blank=True, choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=50, null=True),
        ),
    ]
