# Generated by Django 5.1.3 on 2026-02-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_add_required_vistas'),
        ('settings', '0006_userpreferences_fecha_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsMySQLConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_logico', models.CharField(max_length=100)),
                ('engine', models.CharField(default='django.db.backends.mysql', max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('user', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=255)),
                ('charset', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.empresa')),
            ],
            options={
                'ordering': ['empresa_id', 'nombre_logico'],
                'unique_together': {('empresa', 'nombre_logico')},
            },
        ),
    ]
