# Generated by Django 5.1.3 on 2026-08-23 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_vista_route_name'),
        ('settings', '0007_settingsmysqlconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='vista_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_vista_inicial', to='access_control.vista'),
        ),
    ]
