# Generated by Django 4.2.2 on 2023-07-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatares')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
