# Generated by Django 5.1.3 on 2026-02-10 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAccesoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresar', models.BooleanField(default=False)),
                ('crear', models.BooleanField(default=False)),
                ('modificar', models.BooleanField(default=False)),
                ('eliminar', models.BooleanField(default=False)),
                ('autorizar', models.BooleanField(default=False)),
                ('supervisor', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='access_control.perfilacceso')),
                ('vista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.vista')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('perfil', 'vista'), name='uniq_perfil_vista')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_asignados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.empresa')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.perfilacceso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa'), name='uniq_usuario_empresa_perfil')],
            },
        ),
    ]
