# Generated by Django 5.1.3 on 2026-02-14 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_perfilacceso_perfilaccesodetalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista_nombre', models.CharField(max_length=255)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('RESPONDED', 'RESPONDED'), ('RESOLVED', 'RESOLVED')], default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_note', models.TextField(blank=True)),
                ('email_attempted', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_status', models.CharField(choices=[('SKIPPED', 'SKIPPED'), ('SENT', 'SENT'), ('FAILED', 'FAILED')], default='SKIPPED', max_length=20)),
                ('email_from', models.TextField(blank=True, default='')),
                ('email_error', models.TextField(blank=True, default='')),
                ('email_recipients', models.TextField(blank=True, default='')),
                ('staff_recipient_ids', models.TextField(blank=True, default='')),
                ('notified_staff_count', models.PositiveIntegerField(default=0)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_control.empresa')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_resolved', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_responded', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['solicitante', 'status', 'created_at'], name='access_cont_solicit_86ad5c_idx'), models.Index(fields=['empresa', 'vista_nombre', 'status'], name='access_cont_empresa_6b21a5_idx')],
            },
        ),
    ]
