# Generated by Django 5.1.3 on 2026-08-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_add_required_vistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vista',
            name='route_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
