# Generated by Django 5.1.3 on 2026-08-19 14:57

import django.db.models.deletion
import gestiondte.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoSII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_codigo', models.CharField(db_index=True, max_length=10)),
                ('archivo', models.FileField(upload_to=gestiondte.models.upload_to_certificado)),
                ('password_encrypted', models.BinaryField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_creados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado PFX',
                'verbose_name_plural': 'Certificados PFX',
                'ordering': ['-created_at'],
            },
        ),
    ]
