# Generated by Django 5.1.3 on 2026-08-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadosii',
            name='emisor_certificado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificadosii',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificadosii',
            name='rut_titular',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='certificadosii',
            name='titular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificadosii',
            name='valido_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificadosii',
            name='valido_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
