# Generated by Django 5.1.3 on 2026-08-19 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_add_required_vistas'),
        ('gestiondte', '0002_certificadosii_emisor_certificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CesionRPETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cesion', models.CharField(db_index=True, max_length=64)),
                ('estado_cesion', models.CharField(db_index=True, max_length=80)),
                ('vendedor_rut', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('vendedor_dv', models.CharField(blank=True, max_length=2, null=True)),
                ('deudor_rut', models.CharField(db_index=True, max_length=12)),
                ('deudor_dv', models.CharField(max_length=2)),
                ('deudor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_doc', models.CharField(max_length=10)),
                ('nombre_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('folio_doc', models.CharField(max_length=40)),
                ('fecha_emision', models.DateField(blank=True, db_index=True, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('cedente_rut', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('cedente_dv', models.CharField(blank=True, max_length=2, null=True)),
                ('cedente_razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cedente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cesionario_rut', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('cesionario_dv', models.CharField(blank=True, max_length=2, null=True)),
                ('cesionario_razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cesionario_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_cesion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('monto_cesion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('detectada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_cesion', '-detectada_en'],
                'indexes': [models.Index(fields=['tipo_doc', 'folio_doc'], name='rpetc_cesion_doc_idx')],
                'constraints': [models.UniqueConstraint(fields=('id_cesion', 'deudor_rut', 'deudor_dv', 'tipo_doc', 'folio_doc'), name='rpetc_cesion_identidad_unica')],
            },
        ),
        migrations.CreateModel(
            name='TareaRPETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.CharField(max_length=64, unique=True)),
                ('tipo_consulta', models.CharField(choices=[('DEUDOR', 'Deudor'), ('CEDENTE', 'Cedente'), ('CESIONARIO', 'Cesionario')], max_length=20)),
                ('rut_consultado', models.CharField(max_length=12)),
                ('dv_consultado', models.CharField(max_length=2)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('formato', models.CharField(choices=[('TXT', 'TXT'), ('XML', 'XML')], max_length=4)),
                ('rut_autenticado', models.CharField(blank=True, max_length=12, null=True)),
                ('dv_autenticado', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre_tarea', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=30)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_creado_sii', models.DateTimeField(blank=True, null=True)),
                ('hora_en_proceso_sii', models.DateTimeField(blank=True, null=True)),
                ('hora_terminado_sii', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cantidad_lineas', models.PositiveIntegerField(blank=True, null=True)),
                ('comprimido', models.BooleanField(blank=True, null=True)),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_error', models.TextField(blank=True, null=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('parametros_raw', models.TextField(blank=True, null=True)),
                ('consultada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='empresa_codigo', on_delete=django.db.models.deletion.PROTECT, related_name='tareas_rpetc', to='access_control.empresa', to_field='codigo')),
            ],
            options={
                'ordering': ['-consultada_en'],
            },
        ),
        migrations.CreateModel(
            name='TareaCesionRPETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_detectada', models.DateTimeField(auto_now_add=True)),
                ('rol_consulta', models.CharField(choices=[('DEUDOR', 'Deudor'), ('CEDENTE', 'Cedente'), ('CESIONARIO', 'Cesionario')], max_length=20)),
                ('fila_origen', models.PositiveIntegerField(blank=True, null=True)),
                ('cesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestiondte.cesionrpetc')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cesiones', to='gestiondte.tarearpetc')),
            ],
        ),
        migrations.CreateModel(
            name='CesionRPETCHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=80)),
                ('estado_anterior', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_detectado', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='gestiondte.cesionrpetc')),
                ('tarea_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cesiones', to='gestiondte.tarearpetc')),
            ],
            options={
                'ordering': ['-fecha_detectado'],
            },
        ),
        migrations.AddIndex(
            model_name='tarearpetc',
            index=models.Index(fields=['empresa', 'tipo_consulta'], name='rpetc_tarea_emp_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='tarearpetc',
            index=models.Index(fields=['estado'], name='rpetc_tarea_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='tarearpetc',
            index=models.Index(fields=['fecha_desde', 'fecha_hasta'], name='rpetc_tarea_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='tareacesionrpetc',
            index=models.Index(fields=['rol_consulta'], name='rpetc_tarea_rol_idx'),
        ),
        migrations.AddConstraint(
            model_name='tareacesionrpetc',
            constraint=models.UniqueConstraint(fields=('tarea', 'cesion'), name='rpetc_tarea_cesion_unica'),
        ),
        migrations.AddIndex(
            model_name='cesionrpetchistorial',
            index=models.Index(fields=['cesion', 'fecha_detectado'], name='rpetc_hist_cesion_fecha_idx'),
        ),
    ]
