# Generated by Django 5.1.3 on 2026-08-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0011_create_gestion_dte_auditoria_view'),
        ('gestiondte', '0005_estadocontablecesion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionCesionRPETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glosa', models.TextField(max_length=2000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('cesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='gestiondte.cesionrpetc')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_cesiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_cesiones_rpetc', to='access_control.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_cesiones_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'cesion'], name='revision_cesion_emp_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cesion'), name='revision_cesion_empresa_unica')],
            },
        ),
    ]
