# Generated by Django 5.1.3 on 2026-08-27 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def copiar_glosas_a_comentarios(apps, schema_editor):
    revision_model = apps.get_model('gestiondte', 'RevisionCesionRPETC')
    comentario_model = apps.get_model('gestiondte', 'RevisionCesionComentario')
    comentarios = []
    for revision in revision_model.objects.exclude(glosa='').iterator():
        comentarios.append(comentario_model(
            revision_id=revision.pk,
            comentario=revision.glosa,
            creado_por_id=revision.creado_por_id,
            creado_en=revision.creado_en,
            modificado_en=revision.modificado_en or timezone.now(),
        ))
    comentario_model.objects.bulk_create(comentarios)


def revertir_comentarios_migrados(apps, schema_editor):
    comentario_model = apps.get_model('gestiondte', 'RevisionCesionComentario')
    comentario_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondte', '0006_revisioncesionrpetc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionCesionComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=2000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_revision_cesiones_creados', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='gestiondte.revisioncesionrpetc')),
            ],
            options={
                'ordering': ['creado_en', 'pk'],
            },
        ),
        migrations.RunPython(copiar_glosas_a_comentarios, revertir_comentarios_migrados),
    ]
