# Generated by Django 5.1.3 on 2026-09-21 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondte', '0007_revisioncesioncomentario'),
        ('settings', '0007_settingsmysqlconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionDTEConnectionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('serverbasedte', 'Base DTE'), ('serverauditoriagestiondte', 'Auditoría Gestión DTE'), ('servercontabilidad', 'Contabilidad'), ('serverauditoriacontabilidad', 'Auditoría Contabilidad')], max_length=40, unique=True)),
                ('source_type', models.CharField(choices=[('DJANGO', 'Sistema Django'), ('MYSQL_CONFIG', 'Conexión MySQL')], max_length=20)),
                ('django_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mysql_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestiondte_roles', to='settings.settingsmysqlconnection')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('django_alias__isnull', False), ('mysql_connection__isnull', True), ('source_type', 'DJANGO'), models.Q(('django_alias', ''), _negated=True)), models.Q(('django_alias__isnull', True), ('mysql_connection__isnull', False), ('source_type', 'MYSQL_CONFIG')), _connector='OR'), name='gestiondte_role_source_xor')],
            },
        ),
    ]
