# Generated by Django 5.1.3 on 2026-09-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondte', '0008_gestiondteconnectionrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadosii',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='certificadosii',
            name='updated_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
