# Generated by Django 5.1.3 on 2026-09-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondte', '0009_certificadosii_created_by_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestiondteconnectionrole',
            name='database_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
