# Generated by Django 5.1.3 on 2026-01-28 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0020_alter_propietario_rut'),
        ('control_de_proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='depende_de',
            field=models.ManyToManyField(blank=True, related_name='tareas_dependientes', to='control_de_proyectos.tarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='porcentaje_avance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('BLOQUEADA', 'Bloqueada'), ('TERMINADA', 'Terminada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='profesional_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_de_proyectos.profesional'),
        ),
        migrations.CreateModel(
            name='TareaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_doc', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20)),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('categoria', models.CharField(blank=True, max_length=20)),
                ('fecha_esperada', models.DateField(blank=True, null=True)),
                ('fecha_recibida', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('url_documento', models.URLField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='tareas_documentos/%Y/%m/%d/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('documento_biblioteca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='biblioteca.documento')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='control_de_proyectos.tarea')),
            ],
            options={
                'verbose_name': 'Documento Tarea',
                'verbose_name_plural': 'Documentos Tareas',
                'ordering': ['tarea', 'tipo_doc', 'nombre_documento'],
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='control_de_proyectos.tipotarea'),
        ),
        migrations.CreateModel(
            name='DocumentoRequeridoTipoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('ESPECIFICACION', 'Especificación'), ('DISEÑO', 'Diseño'), ('CODIGO', 'Código'), ('PRUEBA', 'Prueba'), ('DOCUMENTACION', 'Documentación'), ('APROBACION', 'Aprobación'), ('OTRO', 'Otro')], max_length=20)),
                ('tipo_doc', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='control_de_proyectos.tipotarea')),
            ],
            options={
                'verbose_name': 'Documento Requerido por Tipo Tarea',
                'verbose_name_plural': 'Documentos Requeridos por Tipo Tarea',
                'ordering': ['tipo_tarea', 'tipo_doc', 'orden'],
                'unique_together': {('tipo_tarea', 'nombre_documento')},
            },
        ),
    ]
