# Generated by Django 5.1.3 on 2026-01-28 21:30

import control_de_proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_de_proyectos', '0002_tipotarea_tarea_depende_de_tarea_fecha_fin_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareadocumento',
            name='archivo',
            field=models.FileField(blank=True, upload_to=control_de_proyectos.models.archivo_tarea_path, validators=[control_de_proyectos.models.validate_file_extension_tareas]),
        ),
    ]
