# Generated by Django 5.1.3 on 2026-09-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0013_permiso_ver_perfilaccesodetalle_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('ERP', 'ERP'), ('LOCAL', 'Local')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='access_control.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_departamento_codigo_por_empresa')],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('legacy_code', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('ERP', 'ERP'), ('LOCAL', 'Local')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='access_control.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_local_codigo_por_empresa')],
            },
        ),
    ]
