# Generated by Django 5.1.3 on 2026-09-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('comuna', models.CharField(blank=True, default='', max_length=100)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('fono1', models.CharField(blank=True, default='', max_length=30)),
                ('fono2', models.CharField(blank=True, default='', max_length=30)),
                ('fax', models.CharField(blank=True, default='', max_length=30)),
                ('contacto', models.CharField(blank=True, default='', max_length=150)),
                ('email1', models.EmailField(blank=True, default='', max_length=254)),
                ('email2', models.EmailField(blank=True, default='', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
    ]
